from enum import Enum


class AlarmType(str, Enum):
    MASTER_PLC = "MASTER_PLC"
    MASTER_GPS = "MASTER_GPS"
    MASTER_SPS = "MASTER_SPS"
    MASTER_SPS2 = "MASTER_SPS2"
    MASTER_SERVER = "MASTER_SERVER"

    SLAVE_GPS = "SLAVE_GPS"
    # 主机和从机通讯
    SLAVE_MASTER = "SLAVE_MASTER"

    POWER_OVERLOAD = "POWER_OVERLOAD"
